"""
Build cogging feedforward LUT from a slow-velocity sweep CSV.

Usage:
    python scripts/build_cogging_lut.py <cogging.csv> <r|l>

Input CSV columns (produced by sysid.py --calibrate-cogging):
  test         "cogging_sweep"
  angle_rad    LUT-corrected mechanical angle (accumulated, unwrapped)
  voltage_q    Actual q-axis voltage commanded by the velocity PID
  step_target  Velocity setpoint: positive = forward pass, negative = reverse

Output: writes src/cogging_lut_r.h or src/cogging_lut_l.h

Algorithm:
  1. Separate forward (step_target > 0) and reverse (step_target < 0) samples.
  2. Compute electrical angle: (angle_rad * N_POLE_PAIRS) % (2π).
  3. Bin voltage_q by electrical angle into N_LUT equal bins.
  4. Average the per-bin means from the two passes — friction (direction-
     dependent) cancels; position-dependent cogging remains.
  5. Subtract the overall mean so the feedforward is zero-mean (the DC
     component is already handled by the velocity PID's integrator).
  6. Emit the C header.

The feedforward is applied as:
    motor.voltage.q += lut_interp(motor.electricalAngle(), COGGING_LUT, 128)
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd


N_POLE_PAIRS = 7
N_LUT        = 128


def load(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    cal = df[df["test"] == "cogging_sweep"].copy()
    if cal.empty:
        sys.exit(f"ERROR: no 'cogging_sweep' rows found in {path}")
    n_fwd = (cal["step_target"] > 0).sum()
    n_rev = (cal["step_target"] < 0).sum()
    print(f"[info] {len(cal)} cogging sweep rows  ({n_fwd} fwd, {n_rev} rev)",
          file=sys.stderr)
    if n_fwd == 0 or n_rev == 0:
        sys.exit("ERROR: need both forward (step_target > 0) and reverse "
                 "(step_target < 0) rows.")
    return cal


def build_lut(cal: pd.DataFrame) -> np.ndarray:
    fwd = cal[cal["step_target"] > 0]
    rev = cal[cal["step_target"] < 0]

    # Electrical angle in [0, 2π) for each sample.
    elec_fwd = (np.unwrap(fwd["angle_rad"].values) * N_POLE_PAIRS) % (2 * np.pi)
    elec_rev = (np.unwrap(rev["angle_rad"].values) * N_POLE_PAIRS) % (2 * np.pi)

    vq_fwd = fwd["voltage_q"].values
    vq_rev = rev["voltage_q"].values

    # Bin by electrical angle.
    bin_edges = np.linspace(0, 2 * np.pi, N_LUT + 1)

    def bin_mean(elec: np.ndarray, vq: np.ndarray) -> np.ndarray:
        means = np.full(N_LUT, np.nan)
        for i in range(N_LUT):
            mask = (elec >= bin_edges[i]) & (elec < bin_edges[i + 1])
            if mask.any():
                means[i] = vq[mask].mean()
        n_empty = np.isnan(means).sum()
        if n_empty > 0:
            print(f"[warn] {n_empty}/{N_LUT} bins empty — interpolating",
                  file=sys.stderr)
            # Linear interpolation for empty bins.
            idx = np.arange(N_LUT)
            valid = ~np.isnan(means)
            means = np.interp(idx, idx[valid], means[valid],
                              period=N_LUT)
        return means

    mean_fwd = bin_mean(elec_fwd, vq_fwd)
    mean_rev = bin_mean(elec_rev, vq_rev)

    # Average passes: friction (odd in direction) cancels, cogging remains.
    lut = 0.5 * (mean_fwd + mean_rev)

    # Remove mean so feedforward is zero-mean (DC handled by PID integrator).
    lut -= lut.mean()

    rms_mv = np.sqrt(np.mean(lut ** 2)) * 1000
    pk_mv  = (lut.max() - lut.min()) * 1000
    print(f"[info] cogging LUT  RMS={rms_mv:.1f} mV  peak-to-peak={pk_mv:.1f} mV",
          file=sys.stderr)

    return lut


def emit_header(lut: np.ndarray, motor: str, out_path: Path) -> None:
    tag = motor.upper()
    lines = [
        f"// {motor.capitalize()} motor cogging feedforward LUT.",
        f"// Generated by: python scripts/build_cogging_lut.py <cogging.csv> {motor}",
        f"// Indexed by electrical angle in [0, 2pi), 128 points, values in volts.",
        f"// Do not edit by hand — regenerate from calibration data.",
        f"#pragma once",
        f"",
        f"static constexpr float COGGING_LUT_{tag}[{N_LUT}] = {{",
    ]
    for i, v in enumerate(lut):
        comma = "," if i < N_LUT - 1 else ""
        lines.append(f"  {v:+.6f}f{comma}")
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[info] wrote {out_path}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Build cogging feedforward LUT from cogging sweep CSV")
    parser.add_argument("csv",   help="Cogging sweep CSV from sysid.py --calibrate-cogging")
    parser.add_argument("motor", choices=["r", "l"], help="Motor side (r=right, l=left)")
    args = parser.parse_args()

    src_dir  = Path(__file__).parent.parent / "src"
    out_path = src_dir / f"cogging_lut_{args.motor}.h"

    cal = load(args.csv)
    lut = build_lut(cal)
    emit_header(lut, args.motor, out_path)


if __name__ == "__main__":
    main()
