"""
Build encoder correction LUT from calibration CSV.

Usage:
    python scripts/build_encoder_lut.py <cal.csv> <r|l> > src/encoder_lut_r.h

Input CSV columns: test, direction, ref_elec, raw_mech
  direction: F (forward pass) or R (reverse pass)
  ref_elec:  reference electrical angle commanded (radians)
  raw_mech:  raw mechanical angle read from sensor (radians, [0, 2π))

Output: a C header defining ENCODER_LUT_R[128] or ENCODER_LUT_L[128].

Algorithm (Ben Katz):
  1. Convert ref_elec → ref_mech by dividing by N_POLE_PAIRS.
  2. Unwrap both ref_mech and raw_mech to remove discontinuities.
  3. Compute per-sample error = raw_mech_unwrapped - ref_mech_unwrapped.
  4. Interpolate forward and backward passes onto a common fine grid and
     average them to cancel friction asymmetry.
  5. Low-pass filter to remove cogging (7×/rotation) and higher harmonics,
     keeping only eccentricity (1×/rotation).
  6. Subtract mean (DC offset is absorbed by initFOC() zero-angle cal).
  7. Resample to 128 uniform points over [0, 2π).
  8. Emit C header.

Phase ordering check: if the encoder angle decreases while the reference
increases, two motor phase wires are swapped.  The script warns and exits.
"""

import argparse
import sys

import numpy as np
import pandas as pd
from scipy import signal


N_POLE_PAIRS = 7
N_LUT        = 128
N_GRID       = 4096          # Oversampled working grid
F_CUT_CYCS   = 3.0           # Low-pass cutoff in cycles/mechanical rotation


def load(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    cal = df[df["test"] == "encoder_cal"].copy()
    if cal.empty:
        sys.exit(f"ERROR: no 'encoder_cal' rows found in {path}")
    print(f"[info] loaded {len(cal)} calibration rows", file=sys.stderr)
    return cal


def check_phase_ordering(ref_mech_fwd: np.ndarray, raw_mech_fwd: np.ndarray) -> None:
    """Warn if raw_mech decreases while ref_mech increases (swapped phases)."""
    # Take the net change over the first quarter of the forward pass.
    n = len(ref_mech_fwd) // 4
    d_ref = ref_mech_fwd[n] - ref_mech_fwd[0]
    d_raw = raw_mech_fwd[n] - raw_mech_fwd[0]
    if d_ref > 0 and d_raw < 0:
        sys.exit(
            "ERROR: encoder decreases while reference increases — "
            "phase ordering is wrong. Swap two motor wires and recalibrate."
        )
    if abs(d_raw) < 0.1:
        print(
            "WARNING: encoder barely moved during forward pass. "
            "Voltage too low, or motor not connected?",
            file=sys.stderr,
        )


def build_lut(cal: pd.DataFrame) -> np.ndarray:
    fwd = cal[cal["direction"] == "F"].copy()
    bwd = cal[cal["direction"] == "R"].copy()

    if fwd.empty or bwd.empty:
        sys.exit("ERROR: need both F (forward) and R (reverse) rows.")

    # Convert electrical reference to mechanical and unwrap both signals.
    ref_fwd = np.unwrap(fwd["ref_elec"].values / N_POLE_PAIRS)
    raw_fwd = np.unwrap(fwd["raw_mech"].values)

    ref_bwd = np.unwrap(bwd["ref_elec"].values / N_POLE_PAIRS)
    raw_bwd = np.unwrap(bwd["raw_mech"].values)

    check_phase_ordering(ref_fwd, raw_fwd)

    err_fwd = raw_fwd - ref_fwd
    err_bwd = raw_bwd - ref_bwd

    # Reverse the backward pass so both run from low→high ref_mech.
    ref_bwd = ref_bwd[::-1]
    err_bwd = err_bwd[::-1]

    # Interpolate both passes onto a uniform grid spanning one rotation.
    rot_start = max(ref_fwd[0],  ref_bwd[0])
    rot_end   = min(ref_fwd[-1], ref_bwd[-1])
    if rot_end <= rot_start:
        sys.exit("ERROR: forward and backward passes don't overlap.")

    grid = np.linspace(rot_start, rot_end, N_GRID)
    err_f = np.interp(grid, ref_fwd, err_fwd)
    err_r = np.interp(grid, ref_bwd, err_bwd)
    avg   = 0.5 * (err_f + err_r)

    # Low-pass filter: kill cogging (7 cyc/rot) and harmonics.
    # Nyquist = N_GRID/2 cycles/rotation, cutoff at F_CUT_CYCS cycles/rotation.
    Wn = F_CUT_CYCS / (N_GRID / 2)
    b, a = signal.butter(4, Wn)
    smooth = signal.filtfilt(b, a, avg)

    # Remove DC (constant phase offset is calibrated away by initFOC).
    smooth -= smooth.mean()

    # Resample to N_LUT uniform points over [0, 2π).
    lut_ref = np.linspace(0, 2 * np.pi, N_LUT, endpoint=False)
    lut     = np.interp(lut_ref, grid % (2 * np.pi), smooth, period=2 * np.pi)

    rms_mm = np.sqrt(np.mean(smooth ** 2)) * 1000
    pk_mm  = (smooth.max() - smooth.min()) * 1000
    print(f"[info] error RMS={rms_mm:.2f} mrad  peak-to-peak={pk_mm:.2f} mrad",
          file=sys.stderr)

    return lut


def emit_header(lut: np.ndarray, motor: str) -> None:
    tag = motor.upper()
    print(f"// {motor.capitalize()} motor encoder correction LUT.")
    print(f"// Generated by: python scripts/build_encoder_lut.py <cal.csv> {motor}")
    print(f"// Do not edit by hand — regenerate from calibration data.")
    print(f"#pragma once")
    print()
    print(f"static constexpr float ENCODER_LUT_{tag}[{N_LUT}] = {{")
    for i, v in enumerate(lut):
        comma = "," if i < N_LUT - 1 else ""
        print(f"  {v:+.6f}f{comma}")
    print("};")


def main():
    parser = argparse.ArgumentParser(description="Build encoder LUT from calibration CSV")
    parser.add_argument("csv",   help="Calibration CSV from sysid.py --calibrate")
    parser.add_argument("motor", choices=["r", "l"], help="Motor side (r=right, l=left)")
    args = parser.parse_args()

    cal = load(args.csv)
    lut = build_lut(cal)
    emit_header(lut, args.motor)


if __name__ == "__main__":
    main()
